export const initialIngredients = [
    { "name": "aubergine", "level": 1, "copies": 1, "color": "#B085B7" },
    { "name": "avocado", "level": 1, "copies": 1, "color": "#B2EABD" },
    { "name": "banana", "level": 1, "copies": 1, "color": "#FFF58D" },
    { "name": "bao buns", "level": 1, "copies": 1, "color": "#F2F2F2" },
    { "name": "basil", "level": 1, "copies": 1, "color": "#75E050" },
    { "name": "beans", "level": 1, "copies": 1, "color": "#D4B68D" },
    { "name": "beef", "level": 1, "copies": 1, "color": "#F28580" },
    { "name": "cabbage", "level": 1, "copies": 1, "color": "#BAE8A3" },
    { "name": "carrot", "level": 1, "copies": 1, "color": "#FFC55B" },
    { "name": "cheese", "level": 1, "copies": 1, "color": "#FFF78D" },
    { "name": "chicken", "level": 1, "copies": 1, "color": "#FFE16D" },
    { "name": "chili", "level": 1, "copies": 1, "color": "#FF9270" },
    { "name": "chili mayo", "level": 1, "copies": 1, "color": "#FFC575" },
    { "name": "cilantro", "level": 1, "copies": 1, "color": "#75E050" },
    { "name": "corn", "level": 1, "copies": 1, "color": "#FFF78D" },
    { "name": "cornbread", "level": 1, "copies": 1, "color": "#FFE16D" },
    { "name": "cucumber", "level": 1, "copies": 1, "color": "#8AE6A1" },
    { "name": "dairy", "level": 1, "copies": 1, "color": "#FFFDC5" },
    { "name": "egg", "level": 1, "copies": 1, "color": "#FFF78D" },
    { "name": "fish", "level": 1, "copies": 1, "color": "#8DDCFF" },
    { "name": "flour", "level": 1, "copies": 1, "color": "#F2F2F2" },
    { "name": "fries", "level": 1, "copies": 1, "color": "#FFC55B" },
    { "name": "garlic", "level": 1, "copies": 1, "color": "#FFFDC5" },
    { "name": "ginger", "level": 1, "copies": 1, "color": "#FFE16D" },
    { "name": "hamburger buns", "level": 1, "copies": 1, "color": "#FFE16D" },
    { "name": "hoisin sauce", "level": 1, "copies": 1, "color": "#B39D8D" },
    { "name": "lemon", "level": 1, "copies": 1, "color": "#FFF78D" },
    { "name": "lettuce", "level": 1, "copies": 1, "color": "#B2EABD" },
    { "name": "lime", "level": 1, "copies": 1, "color": "#D4F585" },
    { "name": "mango", "level": 1, "copies": 1, "color": "#FFD48D" },
    { "name": "mushroom", "level": 1, "copies": 1, "color": "#EAB4A1" },
    { "name": "mushrooms", "level": 1, "copies": 1, "color": "#EAB4A1" },
    { "name": "naan", "level": 1, "copies": 1, "color": "#FFE6C0" },
    { "name": "oil", "level": 1, "copies": 1, "color": "#F2F2F2" },
    { "name": "onion", "level": 1, "copies": 1, "color": "#EFC5F0" },
    { "name": "pasta", "level": 1, "copies": 1, "color": "#FFEB85" },
    { "name": "peanuts", "level": 1, "copies": 1, "color": "#E1C5A8" },
    { "name": "pineapple", "level": 1, "copies": 1, "color": "#FFFAB0" },
    { "name": "pork", "level": 1, "copies": 1, "color": "#FFB2A0" },
    { "name": "potato", "level": 1, "copies": 1, "color": "#FFD48D" },
    { "name": "rice", "level": 1, "copies": 1, "color": "#FFEB85" },
    { "name": "salt", "level": 1, "copies": 1, "color": "#F2F2F2" },
    { "name": "shrimp", "level": 1, "copies": 1, "color": "#FFB2A0" },
    { "name": "soy sauce", "level": 1, "copies": 1, "color": "#B39D8D" },
    { "name": "spices", "level": 1, "copies": 1, "color": "#E6B22D" },
    { "name": "strawberries", "level": 1, "copies": 1, "color": "#FF90B5" },
    { "name": "sugar", "level": 1, "copies": 1, "color": "#FFFDC5" },
    { "name": "tofu", "level": 1, "copies": 1, "color": "#F7F7F7" },
    { "name": "tomato", "level": 1, "copies": 1, "color": "#FF9B90" },
    { "name": "tortilla", "level": 1, "copies": 1, "color": "#FFEB85" }
  ]